// Generated by gencpp from file my_service/AddStrsResponse.msg
// DO NOT EDIT!


#ifndef MY_SERVICE_MESSAGE_ADDSTRSRESPONSE_H
#define MY_SERVICE_MESSAGE_ADDSTRSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_service
{
template <class ContainerAllocator>
struct AddStrsResponse_
{
  typedef AddStrsResponse_<ContainerAllocator> Type;

  AddStrsResponse_()
    : sum()  {
    }
  AddStrsResponse_(const ContainerAllocator& _alloc)
    : sum(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::my_service::AddStrsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_service::AddStrsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddStrsResponse_

typedef ::my_service::AddStrsResponse_<std::allocator<void> > AddStrsResponse;

typedef boost::shared_ptr< ::my_service::AddStrsResponse > AddStrsResponsePtr;
typedef boost::shared_ptr< ::my_service::AddStrsResponse const> AddStrsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_service::AddStrsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_service::AddStrsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_service::AddStrsResponse_<ContainerAllocator1> & lhs, const ::my_service::AddStrsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_service::AddStrsResponse_<ContainerAllocator1> & lhs, const ::my_service::AddStrsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_service::AddStrsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_service::AddStrsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_service::AddStrsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_service::AddStrsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_service::AddStrsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_service::AddStrsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_service::AddStrsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c5c2c5628b5ddd7119bd2a006302ca9";
  }

  static const char* value(const ::my_service::AddStrsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c5c2c5628b5ddd7ULL;
  static const uint64_t static_value2 = 0x119bd2a006302ca9ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_service::AddStrsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_service/AddStrsResponse";
  }

  static const char* value(const ::my_service::AddStrsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_service::AddStrsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string sum\n"
"\n"
;
  }

  static const char* value(const ::my_service::AddStrsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_service::AddStrsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddStrsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_service::AddStrsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_service::AddStrsResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_SERVICE_MESSAGE_ADDSTRSRESPONSE_H
